---
title: 140.711/2 Advanced Data Science I/II
output:
  html_document:
    toc: true
    theme: cosmo
---


### Instructors

  * [Jeff Leek](http://www.jtleek.com/)
  * [Elizabeth Colantuoni](http://www.biostat.jhsph.edu/~ejohnson/)
  * [Yates Coley](https://twitter.com/yayyyates)

### TAs

  * [John Muschelli](http://biostat.jhsph.edu/~jmuschel/)

### Class Information

* Time: MW 1:30-2:20
* Location: W2009
* Lab Time: W 12:00
* Lab Location: TBA
* Webpage: http://www.jtleek.com/advdatasci
* Old 753and4 Webpages: 
	* http://biostat.jhsph.edu/~jleek/teaching/2011/754/ (2011)
	* http://biostat.jhsph.edu/~jleek/teaching/appliedstat/ (2012)
	* http://jtleek.github.io/jhsph753/ (2013)
	* https://github.com/jtleek/jhsph753and4 (2014)

### Resources

* [Rstudio](http://www.rstudio.com/) 
* [R project](http://www.r-project.org/)
* [Bioconductor](http://bioconductor.org/)
* [Rstudio's cheatsheets](http://www.rstudio.com/resources/cheatsheets/) 
* [swirl](http://swirlstats.com/)
* [DataCamp](https://www.datacamp.com/)

### Books

* [Elements of Data Analytic Style](https://leanpub.com/datastyle)
* [Advanced Data Analysis from an Elementary Point of View](http://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/)
* [Elements of Statistical Learning](statweb.stanford.edu/~tibs/ElemStatLearn/)

### Course Description 

Provides an intensive introduction to applied statistics and data analysis. Trains students to become data scientists capable of both applied data analysis and critical evaluation of the next generation next generation of statistical methods. Since both data analysis and methods development require substantial hands-on experience, focuses on hands-on data analysis.

### Course Objectives
Upon successfully completing this course, students will be able to:

1. Obtain, clean, transform, and process raw data into usable formats
2. Formulate quantitative models to address scientific questions
3. Organize and perform a complete data analysis, from exploration, to analysis, to synthesis, to communication
4. Apply a range of statistical methods for inference and prediction

### Evaluation and feedback

* 55%  =  Data analysis assignments (instructor graded)
* 20%  =  Data analysis reviews (completion)
* 25%  =  Final Project (graded by instructor)

Our goal is to return feedback to you on projects within 1 week of submission. This is an intensive process because it requires individualized feedback so we hope you can bear with us if there are minor delays. 

### Grading philosophy


I believe the purpose of graduate education is to train you to be able to think for yourself and initiate and complete your own projects. I am super excited to talk to you about ideas, work out solutions with you, and help you to figure out statistical methods and/or data analysis. I don't think that graduate school grades are important for this purpose. This means that I don't care very much about graduate student grades. 

That being said, I have to give you a grade, so I will use grades to help communicate your progress. 

1. A - Excellent 
2. B - Passing
3. C - Needs improvement

If you receive A's and B's you would have passed our old qualifying exam on this project and are doing acceptable data analyses. If you receive C's that is my way of letting you know that your work would not pass on the qualifying exam and probably isn't up to speed. I don't feel comfortable assigning percentages to data analyses, but to be able to calculate grades at the completion of the course I will use the following percentages: A = 100%, B = 85%, C = 75% of available points. This will be based on the rubric for data analyses. 

### Data analysis assignments

(For more on my project philosophy see: http://bit.ly/wQT5uI)

Each student will be required to perform two data analysis projects during the course of the class. Students will be given 2 weeks to perform each analysis. The project assignments will consist of a scientific description of the problem. Students are responsible for all stages of each data analysis from obtaining the data to the final report. At the conclusion of each analysis each student must turn in: 

1. A write-up of their data analysis in a synthesized format, with numbered figures and references. (You may also include supplementary material for detailed additional calculations/analyses)
2. A reproducible Rmd file that produces all of the numbers, figures and results in your write-up. 

All documents should be submitted electronically. The grades will be broken down according to the following characterization of your data analysis.  

1. Did you answer the scientific question? (30%)
2. Did you use appropriate statistical methods? (40%)
3. Was your write-up simple, clear, and precise? (20%)
4. Was your code reproducible? (10%)

Keep in mind that this is a data science class In some cases standard methodology will be sufficient to answer the question of interest, in some cases you will need to go beyond the course, and in general the goal is to _answer the question and provide an estimate of uncertainty_. You may speak to your fellow students about specific statistical questions related to the projects, but the overall idea, analysis, and write-up should be your own individual work. You should cite any help you get from fellow students/TAs in your report in standard citation format. 

### Data analysis reviews 

After each data analysis is turned in, they will be randomly assigned to another student for review. Your review will be due one week after it is assigned. Your comments should have the format of a typical peer review. You can find a template and instructions for these reviews here https://github.com/jtleek/reviews. You should include a summary of the analyses and conclusions in the project you are reviewing, any major revisions, and any minor revisions. We will also evaluate each data analysis independently to assign a grade.  

### Final Project 


The final project will have the same format as the data analyses. It will be slightly longer than the weekly projects in terms of space and more in depth in terms of analysis. You will have an opportunity to submit this analysis, get feedback from the instructors, and re-analyze the data on this project. . 

We will give you an option of a final project, but you may also propose a different project to the instructor and as long as it is approved you can do that project. The project should involve data/code that you can obtain, process, analyze, and synthesize yourself. Keep in mind that [real scientists make their own data](http://seanjtaylor.com/post/41463778912/real-scientists-make-their-own-data). You may use any of the methods you learn during the course, or any other methods you know/look up etc. 

### Structure of Class Time 


Class will consist of both lectures on statistical methdology and practice, as well as hands activities. The hands on practice will be assigned in advance of each lecture and will give you time to look it over and come up with questions. The plan will be for students to work on the problem and ask questions, followed by the instructor or a chosen student presenting their solution. 



### Schedule


| Day  | Date  |  Slides | Resources  | 
|---|---|---|---|
| M1  | 2015-08-31  |  [Introduction, Google Slides](https://docs.google.com/presentation/d/1uTRfF-9ANaueR20jknvxR64kWOtxi-zQAv9GDGNFVTQ/edit?usp=sharing) [Introduction, pdf](lecture_notes/Course_Introduction_and_Motivation.pdf) | [day_1.R](code/day_1.R)|
| M1 | 2015-08-31 | [Organizing](http://jtleek.com/advdatasci/lecture_notes/firstexample/#1)| [example project](https://www.dropbox.com/sh/jyd8fmsgofgdaw1/AABjMq1i7t0irrwbgy3c1wlAa?dl=0)|
| W1 | 2015-09-02 | [Introduction, Google Slides](https://docs.google.com/presentation/d/16GqCWSiGclOpus_E2UTQ9SgNNdYpNzDf7rwUHndcj2M/edit?usp=sharing)||
| W1 | 2015-09-02 | [Version control](http://jtleek.com/advdatasci/lecture_notes/versioncontrol/#1)| [rmarkdown lab](https://github.com/SISBID/Module1/blob/gh-pages/labs/rmarkdown-lab.Rmd)|
| W1 | 2015-09-07 | [Getting data](http://jtleek.com/advdatasci/lecture_notes/gettingdata/#1)||
| W2 | 2015-09-07 | [Introduction](https://docs.google.com/presentation/d/1Ly3WbSL-XGqwM9B9rO3zGj5iOTpwb1Alsda-l9dnU_U/edit?usp=sharing)|| 
| W2 | 2015-09-07 | [Getting data](http://jtleek.com/advdatasci/lecture_notes/gettingdata/#1)| [web + api lab](https://github.com/SISBID/Module1/blob/gh-pages/labs/web-api-lab.Rmd) | 
| M3| 2015-09-14 | [Introduction](https://docs.google.com/presentation/d/1URHrfsTU8VPwZrJ4UR1rUnJVWIUckil0q7VcNW81GKQ/edit?usp=sharing)||
| M3| 2015-09-14 | [Tidying data](http://jtleek.com/advdatasci/lecture_notes/tidyingdata/#1)| [dplyr lab](https://github.com/SISBID/Module1/blob/gh-pages/labs/dplyr-lab.Rmd) [merging lab](https://github.com/SISBID/Module1/blob/gh-pages/labs/merging-lab.Rmd)|
| W3 | 2015-09-16 | [Introduction](https://docs.google.com/presentation/d/14OUqCAGcfM-xrz0j9DD_Z1BNP1I_bezC3Exjuo4qjKE/edit?usp=sharing)||
| W3| 2015-09-14 | [Tidying data](http://jtleek.com/advdatasci/lecture_notes/tidyingdata/#1)|[regex lab](https://github.com/SISBID/Module1/blob/gh-pages/labs/regex-lab.Rmd) [final lab](https://github.com/SISBID/Module1/blob/gh-pages/labs/final-lab.Rmd)|
| W4 | 2015-09-23 | [Introduction](https://docs.google.com/presentation/d/1H3beXOXTrfIFK2hNFOpT-bdexmQiNkeuJqCJOwNxT5s/edit?usp=sharing) || 
| W4 | 2015-09-23 | [Exploratory graphs](http://jtleek.com/advdatasci/lecture_notes/exploratory/#1) ||
| M5 | 2015-05-28 | [Introduction](https://docs.google.com/presentation/d/1D-olPtQrSWq8TRCaZKLN-YmJSBr1KbjdPyCQ8hioJz0/edit?usp=sharing)||
| M5 | 2015-09-28 | [Unsupervised analysis I ](http://jtleek.com/advdatasci/lecture_notes/unsupI/#1) ||
| M6 | 2015-10-05 | [Introduction](https://docs.google.com/presentation/d/1W_wKkSHCeMr0cG_Zff8-DkCTSloOMCobKVx6IxeQ8ok/edit?usp=sharing) ||
| M6 | 2015-10-05 | [Dimension reduction](http://jtleek.com/advdatasci/lecture_notes/dimensionReduction/#1) ||
| W6 | 2015-10-07 | [Introduction](https://docs.google.com/presentation/d/1D-olPtQrSWq8TRCaZKLN-YmJSBr1KbjdPyCQ8hioJz0/edit?usp=sharing) || 
| W6 | 2015-10-07 | [Simulation](http://jtleek.com/advdatasci/lecture_notes/simulation/#1) ||
| M8| 2015-10-19 | [Introduction](https://docs.google.com/presentation/d/1K2CEgMe-4euRqNfmtYm5a4LuEsEbHeBMq-z4aEB1dBc/edit?usp=sharing) | |
| M8| 2015-10-19 | [Bootstrapping](https://dl.dropboxusercontent.com/u/7710864/courseraPublic/week7/002bootstrap/index.html#1) | [Stamps example](http://biostat.jhsph.edu/~jleek/teaching/2011/754/lecture10.pdf)|
| W8| 2015-10-21 | [Introduction](https://docs.google.com/presentation/d/19VjV5LDSnpg_Cn_HseGyhfeqFUFEkOcQ0JcIcToPIRU/edit?usp=sharing) | |
| W8| 2015-10-21 | [Multiple Testing](http://jtleek.com/advdatasci/lecture_notes/multipletesting/#1) | |
| M9| 2015-10-26 | [Introduction](https://docs.google.com/presentation/d/1PWoZ_Q5UppZyEtByaGtlUBJU_YISxDKxkGDlsmVj6eU/edit?usp=sharing) | |
| M9| 2015-10-26 | [Multiple Testing](http://jtleek.com/advdatasci/lecture_notes/regularized/#1) | |
| M10 | 2015-11-2 | [Introduction](https://docs.google.com/presentation/d/1C6jF84J8sbLnCoA7vmQdC4TIVne9N2iM0P5QLJpFmh8/edit?usp=sharing) ||
| M10| 2015-11-4 | [Prediction](http://jtleek.com/advdatasci/lecture_notes/prediction/#1) | |
| W10 | 2015-11-4 | [Introduction](https://docs.google.com/presentation/d/1IY0lJtq-BV8vk0Av2Iu9yviVKttopmVhbVVbdo_NfdI/edit?usp=sharing) ||
| W10| 2015-11-4 | [Prediction methods](http://jtleek.com/advdatasci/lecture_notes/predictionMethods/#1) | |
| M11 | 2015-11-9 | [Introduction](https://docs.google.com/presentation/d/1O6qGJiEa4CGhdERvJXtAfFyXX5ThWM6mykixnidyEik/edit?usp=sharing) ||
| M11 | 2015-11-9 | [Prediction methods](http://jtleek.com/advdatasci/lecture_notes/predictionMethods/#1) | |
| W11 | 2015-11-11 | [Introduction](https://docs.google.com/presentation/d/1Cr3q1DKhlW4DEKNNVSe3oku0XLB5NtYq9cUXSnjOSnc/edit?usp=sharing) ||
| W11 | 2015-11-11 | [Prediction methods](http://jtleek.com/advdatasci/lecture_notes/predictionMethods/#1) | |
| M12 | 2015-11-16 | [Introduction](https://docs.google.com/presentation/d/1KPzJbLIW3cb1cxt5TQvclHDifcapdYLdHPwY8ve0bAA/edit?usp=sharing) ||
| M12 | 2015-11-16 | [Prediction methods](http://jtleek.com/advdatasci/lecture_notes/predictionMethods/#1) [Smoothing](http://jtleek.com/advdatasci/lecture_notes/smoothing/#1)| |
| W12 | 2015-11-18 | [Introduction](https://docs.google.com/presentation/d/1R2ZgO7JwZvgn_VKc7_xQAF1S6QINAtpxgUlEBWHDMQo/edit?usp=sharing) ||
| W12 | 2015-11-18 | [Prediction methods](http://jtleek.com/advdatasci/lecture_notes/predictionMethods/#1) [Smoothing](http://jtleek.com/advdatasci/lecture_notes/smoothing/#1)| |
|---|---|---|---|


### Projects

| Project  |  Assigned Date  |  Due Date | Link  |  Description |
|---|---|---|---|---|
| Project 1 | 2015-09-02  | 2015-09-14 | [Project 1](https://www.crowdgrader.org/crowdgrader/venues/view_venue/1329) | Guns and homicide, email for link| [feedback](http://jtleek.com/advdatasci/code/project1-resources.html) |
| Project 2 | 2015-09-16 | 2015-09-27 | [Project 2](https://www.crowdgrader.org/crowdgrader/venues/view_venue/1395) | Fitbit activity, email for link|
| Final Project | 2015-10-07 | 2015-10-16 | [Final project](https://github.com/jtleek/advdatasci/blob/gh-pages/projects/final.md) | Please submit via Courseplus|
| 712 Project 1 | 2015-11-04 | 2015-11-25 (poster)/ 2015-12-2 (app) | [Project](https://github.com/jtleek/advdatasci/blob/gh-pages/projects/project1-712.md) | Please submit via Courseplus/Github|
|---|---|---|---|---|



### Miscellaneous

Feel free to submit typos/errors/etc via the github repository associated with the class: 
https://github.com/jtleek/advdatasci

This web-page is modified from Andrew Jaffe's [Summer 2015 R course](http://www.aejaffe.com/summerR_2015/), which also has great material if you want to learn R. 

```{r, eval = FALSE, echo = FALSE}
## Render this file:
rmarkdown::render('index.Rmd')
```

This page was last updated on `r Sys.time()` Eastern Time.